### ISSUE TITLE
Octaves don't shift for upper set of computer keys

### ISSUE THREAD

**Issue by dentistformyeye** [igorski/efflux-tracker#44]
Computer keys in the Q row and number row are stuck on C-4 regardless of the octave setting using [ and ]. I'd like the pitches of the upper computer keys to always be one octave higher than the pitches of the corresponding lower computer keys.

In addition, I'd like to have the notes in each set of keys continue to increase in pitch. Currently, the pitches wrap around before reaching the 8th note of the octave: if Z plays C-2, then the comma key also plays C-2.
I'd like the comma key and the Q key to both play C-3 instead. Following that pattern, the period key, the i key, and the O key would respectively play D-3, C-4, and D-4.

**Comment by igorski** [comment]
Hi, the Q row can shift its octaves separately from the Z row by using the - and + keys.

The pitch wrap around is however a horrible bug, thanks for pointing that one out! This has been resolved in b322a54 which will be automatically deployed onto the website within the next half hour or so.

**Comment by dentistformyeye** [comment]
My bad, I should have read the help pages again. Thanks for the fix!

**Comment by dentistformyeye** [comment]
If you don't mind my asking, what is Efflux licensed under?

**Comment by igorski** [comment]
> If you don't mind my asking, what is Efflux licensed under?

All my repositories are made available under MIT license. I have also added the LICENSE file to the repository root as I noticed it was missing :)
